version: "3.9"

services:
  indexer-1:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 0 --end-block 1000000

  indexer-2:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 1000000 --end-block 2000000

  indexer-3:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 2000000 --end-block 3000000

  indexer-4:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 3000000 --end-block 4000000

  indexer-5:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 4000000 --end-block 5000000

  indexer-6:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 5000000 --end-block 6000000

  indexer-7:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 6000000 --end-block 7000000
  
  indexer-8:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 7000000 --end-block 8000000

  indexer-9:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 8000000 --end-block 9000000

  indexer-10:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 9000000 --end-block 10000000


  indexer-11:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 9000000 --end-block 10000000

  indexer-12:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 11000000 --end-block 12000000

  indexer-13:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 12000000 --end-block 13000000

  indexer-14:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 14000000 --end-block 15000000

  indexer-15:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 15000000 --end-block 16000000

  indexer-16:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 16000000 --end-block 17000000

  indexer-17:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --rpcs ${RPC_URLS} --database ${DATABASE_URL} --ws ${WS_URL} --start-block 17000000