version: "3.9"

services:
  indexer-1:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 16000000 --end-block 20000000
  
  indexer-2:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 20000000 --end-block 25000000

  indexer-3:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 25000000 --end-block 30000000

  indexer-4:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 30000000 --end-block 35000000

  indexer-5:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 35000000 --end-block 40000000

  indexer-6:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: always
    command: evm-indexer --chain 137 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --ws ${WS_URL} --start-block 40000000