version: "3.9"

services:
  polygon-indexer-1:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 0 --end-block 2000000 --batch-size 500

  polygon-indexer-2:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 2000000 --end-block 4000000 --batch-size 500

  polygon-indexer-3:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 4000000 --end-block 6000000 --batch-size 500

  polygon-indexer-4:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 6000000 --end-block 8000000 --batch-size 500

  polygon-indexer-5:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 8000000 --end-block 10000000 --batch-size 500

  polygon-indexer-6:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 12000000 --end-block 14000000 --batch-size 500

  polygon-indexer-7:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 14000000 --end-block 16000000 --batch-size 500

  polygon-indexer-8:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 16000000 --end-block 18000000 --batch-size 500

  polygon-indexer-9:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 18000000 --end-block 20000000 --batch-size 500
  
  polygon-indexer-10:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 20000000 --end-block 22000000 --batch-size 500

  polygon-indexer-11:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 22000000 --end-block 24000000 --batch-size 500

  polygon-indexer-12:
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    restart: on-failure
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 24000000 --end-block 26000000 --batch-size 500

  polygon-indexer-13:
    restart: on-failure
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --start-block 26000000 --batch-size 500

  polygon-indexer-14:
    restart: always
    image: ghcr.io/kindynosmx/evm-indexer:main
    env_file:
      - ./.env
    command: evm-indexer --chain 56 --rpcs ${RPC_URLS} --database ${DATABASE_URL} --ws ${WS_URL} --new-blocks-only